id: boleto_automation
namespace: finance.automation

tasks:
  - id: working_directory
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/millenialperson1995/schedule-bill.git
        branch: master

      - id: process_boletos
        type: io.kestra.plugin.scripts.python.Commands
        env:
          # Se não conseguir usar Secrets, coloque os valores aqui (Cuidado: ficarão visíveis no arquivo)
          DEEPSEEK_API_KEY: "sk-9621c873aa0b4fc5999cc45228ac4ad2"
          MONGODB_URI: "mongodb://admin:admin@127.0.0.1:27017/"
          TELEGRAM_BOT_TOKEN: "8217740882:AAHqF5MIorkKN-feQY5QcFm8XSv0zujdMqs"
          TELEGRAM_CHAT_ID: "1793948672"
        commands:
          - pip install -r requirements.txt
          - python process_boletos.py

      - id: check_deadlines
        type: io.kestra.plugin.scripts.python.Commands
        env:
          DEEPSEEK_API_KEY: "sk-9621c873aa0b4fc5999cc45228ac4ad2"
          MONGODB_URI: "mongodb://admin:admin@127.0.0.1:27017/"
          TELEGRAM_BOT_TOKEN: "8217740882:AAHqF5MIorkKN-feQY5QcFm8XSv0zujdMqs"
          TELEGRAM_CHAT_ID: "1793948672"
        commands:
          - pip install -r requirements.txt
          - python check_deadlines.py

# Triggers (Schedules)
triggers:
  - id: schedule_process
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/10 * * * *" # Every 10 minutes
