id: boleto_drive_automation
namespace: finance.automation

variables:
  # ID da pasta de INPUT e PROCESSED
  drive_folder_id: "1XwbNQq8m3IuGTmPdMKMHGP2DpDtd0uc9"
  processed_folder_id: "1Hg3qZRuTw88jLlrIJm-8YaK_zgu3qtQk"

  # Credenciais do Google (Service Account)
  # IMPORTANTE: Use o arquivo CONFIG_KESTRA_LOCAL.txt para pegar a chave real
  gcp_creds: |
    {
      "type": "service_account",
      "project_id": "PLACEHOLDER",
      "private_key": "PLACEHOLDER",
      "client_email": "PLACEHOLDER"
    }

tasks:
  - id: list_files
    type: io.kestra.plugin.googleworkspace.drive.List
    serviceAccount: "{{ vars.gcp_creds }}"
    query: "'{{ vars.drive_folder_id }}' in parents and trashed = false"

  - id: process_each_file
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{ outputs.list_files.files }}"
    tasks:
      - id: download_file
        type: io.kestra.plugin.googleworkspace.drive.Download
        serviceAccount: "{{ vars.gcp_creds }}"
        fileId: "{{ fromJson(taskrun.value).id }}"

      - id: working_directory
        type: io.kestra.plugin.core.flow.WorkingDirectory
        tasks:
          - id: clone_repo
            type: io.kestra.plugin.git.Clone
            url: https://github.com/millenialperson1995/schedule-bill.git
            branch: master
            
          - id: run_python_processor
            type: io.kestra.plugin.scripts.python.Commands
            inputFiles:
              "input_boletos/{{ fromJson(taskrun.value).name }}": "{{ parent.outputs.download_file.uri }}"
            env:
              DEEPSEEK_API_KEY: "PLACEHOLDER"
              MONGODB_URI: "mongodb://admin:admin@host.docker.internal:27017/"
              TELEGRAM_BOT_TOKEN: "PLACEHOLDER"
              TELEGRAM_CHAT_ID: "PLACEHOLDER"
            commands:
              - pip install -r requirements.txt
              - python process_boletos.py

      - id: upload_to_processed
        type: io.kestra.plugin.googleworkspace.drive.Upload
        serviceAccount: "{{ vars.gcp_creds }}"
        from: "{{ outputs.download_file.uri }}"
        parents: 
          - "{{ vars.processed_folder_id }}"
        name: "{{ fromJson(taskrun.value).name }}"
        contentType: "application/pdf"

      - id: delete_from_input
        type: io.kestra.plugin.googleworkspace.drive.Delete
        serviceAccount: "{{ vars.gcp_creds }}"
        fileId: "{{ fromJson(taskrun.value).id }}"

# Executa a cada 1 minuto
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/1 * * * *"
